services:
  - type: web
    name: tiktok-uploader
    env: python
    plan: free
    region: oregon
    runtime: python
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.18
      - key: PIP_NO_CACHE_DIR
        value: 1 